spring:
  application:
    name: palm-zjnu

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote
    password: "remote"
    url: jdbc:mysql://sunway.icu:3306/palm_zjnu

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

picture-path:
  dir: E:/Projects/repos/palm-zjnu-backend/pictures/
#  dir: /root/images/

dev-server: http://sunway.icu:8080